-- Add missing columns to organization_config table
-- Run this in Supabase SQL Editor

ALTER TABLE organization_config
ADD COLUMN IF NOT EXISTS ein TEXT,
ADD COLUMN IF NOT EXISTS organization_type TEXT DEFAULT 'nonprofit',
ADD COLUMN IF NOT EXISTS tax_exempt_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS years_established INTEGER,
ADD COLUMN IF NOT EXISTS annual_budget NUMERIC,
ADD COLUMN IF NOT EXISTS staff_size INTEGER,
ADD COLUMN IF NOT EXISTS board_size INTEGER,
ADD COLUMN IF NOT EXISTS website_url TEXT,
ADD COLUMN IF NOT EXISTS contact_email TEXT,
ADD COLUMN IF NOT EXISTS contact_phone TEXT,
ADD COLUMN IF NOT EXISTS primary_focus_area TEXT,
ADD COLUMN IF NOT EXISTS secondary_focus_areas JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS service_regions JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS languages_served JSONB DEFAULT '["English"]',
ADD COLUMN IF NOT EXISTS key_programs JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS target_populations JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS key_partnerships JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS accreditations JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS preferred_grant_size_min NUMERIC,
ADD COLUMN IF NOT EXISTS preferred_grant_size_max NUMERIC,
ADD COLUMN IF NOT EXISTS grant_writing_capacity TEXT DEFAULT 'moderate',
ADD COLUMN IF NOT EXISTS key_impact_metrics JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS success_stories JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS previous_grants JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS funding_priorities JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS custom_search_keywords JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS excluded_keywords JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS expansion_plans TEXT,
ADD COLUMN IF NOT EXISTS donor_restrictions TEXT,
ADD COLUMN IF NOT EXISTS matching_fund_capacity NUMERIC DEFAULT 0;
